export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const LOGOUT_USER = 'LOGOUT_USER';

export const CHECKING_TOKEN = 'CHECKING_TOKEN';
export const CHECKING_TOKEN_SUCCESS = 'CHECKING_TOKEN_SUCCESS';
export const REFRESHING_TOKEN = 'REFRESHING_TOKEN';
export const REFRESHING_TOKEN_SUCCESS = 'REFRESHING_TOKEN_SUCCESS';
