export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAIL = 'SIGNUP_USER_FAIL';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const LOGOUT_USER = 'LOGOUT_USER';

export const CHECKING_TOKEN = 'CHECKING_TOKEN';
export const CHECKING_TOKEN_SUCCESS = 'CHECKING_TOKEN_SUCCESS';
export const REFRESHING_TOKEN = 'REFRESHING_TOKEN';
export const REFRESHING_TOKEN_SUCCESS = 'REFRESHING_TOKEN_SUCCESS';

export const REQUEST_COVERS = 'REQUEST_COVERS';
export const REQUEST_COVERS_SUCCESS = 'REQUEST_COVERS_SUCCESS';

export const POPULAR_COVERS_SUCCESS = 'POPULAR_COVERS_SUCCESS';
export const NEWEST_COVERS_SUCCESS = 'NEWEST_COVERS_SUCCESS';
