export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAIL = 'SIGNUP_USER_FAIL';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const LOGOUT_USER = 'LOGOUT_USER';

export const FETCH_FB_TOKEN = 'FETCH_FB_TOKEN';
export const FETCH_FB_TOKEN_SUCCESS = 'FETCH_FB_TOKEN_SUCCESS';
export const FETCH_FB_TOKEN_FAIL = 'FETCH_FB_TOKEN_FAIL';

export const REFRESHING_TOKEN = 'REFRESHING_TOKEN';
export const REFRESHING_TOKEN_SUCCESS = 'REFRESHING_TOKEN_SUCCESS';
export const REFRESHING_TOKEN_FAIL = 'REFRESHING_TOKEN_FAIL';

export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS';
export const FETCH_CURRENT_USER_FAIL = 'FETCH_CURRENT_USER_FAIL';

export const FETCH_LIKED_COVERS = 'FETCH_LIKED_COVERS';
export const FETCH_LIKED_COVERS_SUCCESS = 'FETCH_LIKED_COVERS_SUCCESS';
export const FETCH_LIKED_COVERS_FAIL = 'FETCH_LIKED_COVERS_FAIL';

export const REQUEST_COVERS = 'REQUEST_COVERS';
export const REQUEST_COVERS_SUCCESS = 'REQUEST_COVERS_SUCCESS';

export const POPULAR_COVERS_SUCCESS = 'POPULAR_COVERS_SUCCESS';
export const NEWEST_COVERS_SUCCESS = 'NEWEST_COVERS_SUCCESS';
